package com.flipfit.db;

import com.flipfit.core.User;
import com.flipfit.core.Role;
import com.flipfit.db.mapper.RoleArgumentFactory;
import com.flipfit.db.mapper.RoleColumnMapper;
import org.jdbi.v3.sqlobject.customizer.Bind;
import org.jdbi.v3.sqlobject.customizer.BindBean;
import org.jdbi.v3.sqlobject.config.RegisterArgumentFactory;
import org.jdbi.v3.sqlobject.config.RegisterColumnMapper;
import org.jdbi.v3.sqlobject.statement.GetGeneratedKeys;
import org.jdbi.v3.sqlobject.statement.SqlQuery;
import org.jdbi.v3.sqlobject.statement.SqlUpdate;
import org.jdbi.v3.sqlobject.statement.UseRowMapper;

import java.util.List;
import java.util.Optional;

@RegisterColumnMapper(RoleColumnMapper.class)
@RegisterArgumentFactory(RoleArgumentFactory.class)
public interface UserDAO {

    @SqlUpdate("CREATE TABLE IF NOT EXISTS users (id VARCHAR(50) PRIMARY KEY, name VARCHAR(50), email VARCHAR(50) UNIQUE, password VARCHAR(50), role VARCHAR(50))")
    void createTable();

    @SqlUpdate("INSERT INTO users (id, name, email, password, role) VALUES (:id, :name, :email, :password, :role)")
    @GetGeneratedKeys("id") // Assuming 'id' is generated by the database
    String insert(@BindBean User user);

    @SqlQuery("SELECT id, name, email, password, role FROM users WHERE id = :id")
    Optional<User> findById(@Bind("id") String id);

    @SqlQuery("SELECT id, name, email, password, role FROM users WHERE email = :email")
    Optional<User> findByEmail(@Bind("email") String email);

    @SqlQuery("SELECT id, name, email, password, role FROM users")
    List<User> findAll();

    @SqlUpdate("UPDATE users SET name = :name, email = :email, password = :password, role = :role WHERE id = :id")
    void update(@BindBean User user);

    @SqlUpdate("DELETE FROM users WHERE id = :id")
    void deleteById(@Bind("id") String id);
}
